apiVersion: v1
kind: Secret
metadata:
  name: hosped-pagamento-secret
  namespace: default
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "pagamentos_pass"
  SPRING_RABBITMQ_PASSWORD: "guest"
  MAIL_USERNAME: ""
  MAIL_PASSWORD: ""
