apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: default
type: Opaque
stringData:
  POSTGRES_PASSWORD: "postgres"
  PAGAMENTO_DB_PASSWORD: "pagamentos_pass"
  QUARTO_DB_PASSWORD: "quartos_pass"
  USERS_DB_PASSWORD: "users_pass"
  RESERVA_DB_PASSWORD: "reserva_pass"
