server:
  port: ${PORT:${SERVER_PORT:8080}}

spring:
  application:
    name: api-gateway

jwt:
  secret: ${JWT_SECRET}
  issuer: ${JWT_ISSUER}

services:
  pagamentos-url: ${PAGAMENTO_SERVICE_URL:http://localhost:8083}
  reservas-url: ${RESERVA_SERVICE_URL:http://localhost:8081}
  quartos-url: ${QUARTO_SERVICE_URL:http://localhost:8084}
  users-url: ${USERS_SERVICE_URL:http://localhost:8085}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
  info:
    env:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    environment: ${APP_ENVIRONMENT:LOCAL}
