app:
  environment: ${APP_ENVIRONMENT:DEV}

spring:
  jpa:
    show-sql: true

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

management:
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.user.api_users: DEBUG

info:
  app:
    environment: ${APP_ENVIRONMENT:DEV}
