spring:
  application:
    name: ${SPRING_APPLICATION_NAME:ms-users}

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/hosped_users}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:users_pass}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${SERVER_PORT:8085}

jwt:
  secret: ${JWT_SECRET}
  issuer: ${JWT_ISSUER}
  expiration: ${JWT_EXPIRATION}

users:
  seed-admin:
    enabled: ${USERS_SEED_ADMIN_ENABLED:false}
    cpf: ${USERS_SEED_ADMIN_CPF:00000000000}
    password: ${USERS_SEED_ADMIN_PASSWORD:Admin@123}
    name: ${USERS_SEED_ADMIN_NAME:Administrador Local}
