apiVersion: v1
kind: Secret
metadata:
  name: hosped-users-secret
  namespace: default
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "users_pass"
  JWT_SECRET: "sua-chave-secreta-jwt-aqui"
  USERS_SEED_ADMIN_PASSWORD: "Admin@123"
