name: CI/CD - Hosped Pagamento

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
      - "feature/**"
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "hosped-pagamento/**"
      - ".github/workflows/hosped-pagamento.yml"
      - ".github/workflows/_java-service-ci-cd.yml"

jobs:
  service:
    uses: ./.github/workflows/_java-service-ci-cd.yml
    with:
      service_name: Hosped Pagamento
      service_path: hosped-pagamento
      docker_image: hosped-pagamento
      dockerhub_namespace: ${{ vars.DOCKERHUB_NAMESPACE }}
      sonar_project_key: ${{ vars.SONAR_PROJECT_KEY_HOSPED_PAGAMENTO }}
      sonar_organization: ${{ vars.SONAR_ORGANIZATION }}
      sonar_host_url: ${{ vars.SONAR_HOST_URL }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      RENDER_DEPLOY_HOOK_DEV: ${{ secrets.RENDER_DEPLOY_HOOK_HOSPED_PAGAMENTO_DEV }}
      RENDER_DEPLOY_HOOK_HOMOL: ${{ secrets.RENDER_DEPLOY_HOOK_HOSPED_PAGAMENTO_HOMOL }}
